#pragma once


class Expressions
{
public:

    void compute(double a1, double a2, double lever, double theta0);

    // Input arguments:
    double a1 = 0;
    double a2 = 0;
    double lever = 0;
    double theta0 = 0;

    // Results:
    double ex = 0;
    double ey = 0;
    double ez = 0;

    // Intermediate expressions:
    double _lever_pow_2 = 0;
    double _a2_pow_2 = 0;
    double __add_a2_pow_2 = 0;
    double __add_a2_pow_2_add_lever_pow_2 = 0;
    double _1_div_sqrt__lpar__add_a2_pow_2_add_lever_pow_2_rpar__ = 0;
    double _lever_pow_4 = 0;
    double _a1_pow_2 = 0;
    double __add_a1_pow_2_mul_a2_pow_2 = 0;
    double __add_a1_pow_2_mul_a2_pow_2_add_lever_pow_4 = 0;
    double _1_div___lpar__add_a1_pow_2_mul_a2_pow_2_add_lever_pow_4_rpar__ = 0;
    double _lever_pow_5 = 0;
    double _sin__lpar_theta0_rpar__ = 0;
    double _lever_pow_5_mul_sin__lpar_theta0_rpar__ = 0;
    double _lever_pow_8 = 0;
    double _lever_pow_6 = 0;
    double __add_a1_pow_2_mul_lever_pow_6 = 0;
    double _a1_pow_4 = 0;
    double _a2_pow_4 = 0;
    double __add_a1_pow_4_mul_a2_pow_4 = 0;
    double __add_a2_pow_2_mul_lever_pow_6 = 0;
    double _sin__lpar_theta0_rpar___pow_2 = 0;
    double __add_2_mul_lever_pow_8_mul_sin__lpar_theta0_rpar___pow_2 = 0;
    double _a1_pow_2_mul_a2_pow_4_mul_lever_pow_2 = 0;
    double _a1_pow_4_mul_a2_pow_2_mul_lever_pow_2 = 0;
    double _2_mul_a1_pow_2_mul_lever_pow_6_mul_sin__lpar_theta0_rpar___pow_2 = 0;
    double _2_mul_a2_pow_2_mul_lever_pow_6_mul_sin__lpar_theta0_rpar___pow_2 = 0;
    double _a2_pow_3 = 0;
    double __add_2_mul_a1_mul_a2_pow_3_mul_lever_pow_4_mul_sin__lpar_theta0_rpar___pow_2 = 0;
    double _a1_pow_3 = 0;
    double __add_2_mul_a1_pow_3_mul_a2_mul_lever_pow_4_mul_sin__lpar_theta0_rpar___pow_2 = 0;
    double __add_2_mul_a1_pow_2_mul_a2_pow_2_mul_lever_pow_4_mul_sin__lpar_theta0_rpar___pow_2 = 0;
    double _2_mul_a1_mul_a2_mul_lever_pow_6_mul_sin__lpar_theta0_rpar___pow_2 = 0;
    double _2_mul_a1_pow_3_mul_a2_pow_3_mul_lever_pow_2_mul_sin__lpar_theta0_rpar___pow_2 = 0;
    double __add_a1_pow_4_mul_a2_pow_4_add_a1_pow_4_mul_a2_pow_2_mul_lever_pow_2_add_2_mul_a1_pow_3_mul_a2_pow_3_mul_lever_pow_2_mul_sin__lpar_theta0_rpar___pow_2_add_2_mul_a1_pow_3_mul_a2_mul_lever_pow_4_mul_sin__lpar_theta0_rpar___pow_2_add_a1_pow_2_mul_a2_pow_4_mul_lever_pow_2_add_2_mul_a1_pow_2_mul_a2_pow_2_mul_lever_pow_4_mul_sin__lpar_theta0_rpar___pow_2_add_2_mul_a1_pow_2_mul_lever_pow_6_mul_sin__lpar_theta0_rpar___pow_2_add_a1_pow_2_mul_lever_pow_6_add_2_mul_a1_mul_a2_pow_3_mul_lever_pow_4_mul_sin__lpar_theta0_rpar___pow_2_add_2_mul_a1_mul_a2_mul_lever_pow_6_mul_sin__lpar_theta0_rpar___pow_2_add_2_mul_a2_pow_2_mul_lever_pow_6_mul_sin__lpar_theta0_rpar___pow_2_add_a2_pow_2_mul_lever_pow_6_add_2_mul_lever_pow_8_mul_sin__lpar_theta0_rpar___pow_2_add_lever_pow_8 = 0;
    double _sqrt__lpar__add_a1_pow_4_mul_a2_pow_4_add_a1_pow_4_mul_a2_pow_2_mul_lever_pow_2_add_2_mul_a1_pow_3_mul_a2_pow_3_mul_lever_pow_2_mul_sin__lpar_theta0_rpar___pow_2_add_2_mul_a1_pow_3_mul_a2_mul_lever_pow_4_mul_sin__lpar_theta0_rpar___pow_2_add_a1_pow_2_mul_a2_pow_4_mul_lever_pow_2_add_2_mul_a1_pow_2_mul_a2_pow_2_mul_lever_pow_4_mul_sin__lpar_theta0_rpar___pow_2_add_2_mul_a1_pow_2_mul_lever_pow_6_mul_sin__lpar_theta0_rpar___pow_2_add_a1_pow_2_mul_lever_pow_6_add_2_mul_a1_mul_a2_pow_3_mul_lever_pow_4_mul_sin__lpar_theta0_rpar___pow_2_add_2_mul_a1_mul_a2_mul_lever_pow_6_mul_sin__lpar_theta0_rpar___pow_2_add_2_mul_a2_pow_2_mul_lever_pow_6_mul_sin__lpar_theta0_rpar___pow_2_add_a2_pow_2_mul_lever_pow_6_add_2_mul_lever_pow_8_mul_sin__lpar_theta0_rpar___pow_2_add_lever_pow_8_rpar__ = 0;
    double __add_a2_mul_sqrt__lpar__add_a1_pow_4_mul_a2_pow_4_add_a1_pow_4_mul_a2_pow_2_mul_lever_pow_2_add_2_mul_a1_pow_3_mul_a2_pow_3_mul_lever_pow_2_mul_sin__lpar_theta0_rpar___pow_2_add_2_mul_a1_pow_3_mul_a2_mul_lever_pow_4_mul_sin__lpar_theta0_rpar___pow_2_add_a1_pow_2_mul_a2_pow_4_mul_lever_pow_2_add_2_mul_a1_pow_2_mul_a2_pow_2_mul_lever_pow_4_mul_sin__lpar_theta0_rpar___pow_2_add_2_mul_a1_pow_2_mul_lever_pow_6_mul_sin__lpar_theta0_rpar___pow_2_add_a1_pow_2_mul_lever_pow_6_add_2_mul_a1_mul_a2_pow_3_mul_lever_pow_4_mul_sin__lpar_theta0_rpar___pow_2_add_2_mul_a1_mul_a2_mul_lever_pow_6_mul_sin__lpar_theta0_rpar___pow_2_add_2_mul_a2_pow_2_mul_lever_pow_6_mul_sin__lpar_theta0_rpar___pow_2_add_a2_pow_2_mul_lever_pow_6_add_2_mul_lever_pow_8_mul_sin__lpar_theta0_rpar___pow_2_add_lever_pow_8_rpar__ = 0;
    double _lever_pow_3 = 0;
    double __add_a2_pow_2_mul_lever_pow_3_mul_sin__lpar_theta0_rpar__ = 0;
    double _a1_mul_a2_pow_3_mul_lever_mul_sin__lpar_theta0_rpar__ = 0;
    double __add_a1_mul_a2_mul_lever_pow_3_mul_sin__lpar_theta0_rpar__ = 0;
    double _a1_mul_a2_pow_3_mul_lever_mul_sin__lpar_theta0_rpar___add_a1_mul_a2_mul_lever_pow_3_mul_sin__lpar_theta0_rpar___add_a2_pow_2_mul_lever_pow_3_mul_sin__lpar_theta0_rpar___add_a2_mul_sqrt__lpar__add_a1_pow_4_mul_a2_pow_4_add_a1_pow_4_mul_a2_pow_2_mul_lever_pow_2_add_2_mul_a1_pow_3_mul_a2_pow_3_mul_lever_pow_2_mul_sin__lpar_theta0_rpar___pow_2_add_2_mul_a1_pow_3_mul_a2_mul_lever_pow_4_mul_sin__lpar_theta0_rpar___pow_2_add_a1_pow_2_mul_a2_pow_4_mul_lever_pow_2_add_2_mul_a1_pow_2_mul_a2_pow_2_mul_lever_pow_4_mul_sin__lpar_theta0_rpar___pow_2_add_2_mul_a1_pow_2_mul_lever_pow_6_mul_sin__lpar_theta0_rpar___pow_2_add_a1_pow_2_mul_lever_pow_6_add_2_mul_a1_mul_a2_pow_3_mul_lever_pow_4_mul_sin__lpar_theta0_rpar___pow_2_add_2_mul_a1_mul_a2_mul_lever_pow_6_mul_sin__lpar_theta0_rpar___pow_2_add_2_mul_a2_pow_2_mul_lever_pow_6_mul_sin__lpar_theta0_rpar___pow_2_add_a2_pow_2_mul_lever_pow_6_add_2_mul_lever_pow_8_mul_sin__lpar_theta0_rpar___pow_2_add_lever_pow_8_rpar___add_lever_pow_5_mul_sin__lpar_theta0_rpar__ = 0;
    double _2_mul_lever_mul___lpar_a1_mul_a2_pow_3_mul_lever_mul_sin__lpar_theta0_rpar___add_a1_mul_a2_mul_lever_pow_3_mul_sin__lpar_theta0_rpar___add_a2_pow_2_mul_lever_pow_3_mul_sin__lpar_theta0_rpar___add_a2_mul_sqrt__lpar__add_a1_pow_4_mul_a2_pow_4_add_a1_pow_4_mul_a2_pow_2_mul_lever_pow_2_add_2_mul_a1_pow_3_mul_a2_pow_3_mul_lever_pow_2_mul_sin__lpar_theta0_rpar___pow_2_add_2_mul_a1_pow_3_mul_a2_mul_lever_pow_4_mul_sin__lpar_theta0_rpar___pow_2_add_a1_pow_2_mul_a2_pow_4_mul_lever_pow_2_add_2_mul_a1_pow_2_mul_a2_pow_2_mul_lever_pow_4_mul_sin__lpar_theta0_rpar___pow_2_add_2_mul_a1_pow_2_mul_lever_pow_6_mul_sin__lpar_theta0_rpar___pow_2_add_a1_pow_2_mul_lever_pow_6_add_2_mul_a1_mul_a2_pow_3_mul_lever_pow_4_mul_sin__lpar_theta0_rpar___pow_2_add_2_mul_a1_mul_a2_mul_lever_pow_6_mul_sin__lpar_theta0_rpar___pow_2_add_2_mul_a2_pow_2_mul_lever_pow_6_mul_sin__lpar_theta0_rpar___pow_2_add_a2_pow_2_mul_lever_pow_6_add_2_mul_lever_pow_8_mul_sin__lpar_theta0_rpar___pow_2_add_lever_pow_8_rpar___add_lever_pow_5_mul_sin__lpar_theta0_rpar___rpar___mul_sin__lpar_theta0_rpar___div___lpar_sqrt__lpar__add_a2_pow_2_add_lever_pow_2_rpar___mul___lpar__add_a1_pow_2_mul_a2_pow_2_add_lever_pow_4_rpar___rpar__ = 0;
    double __add_a1_pow_2 = 0;
    double __add_a1_pow_2_add_lever_pow_2 = 0;
    double _1_div_sqrt__lpar__add_a1_pow_2_add_lever_pow_2_rpar__ = 0;
    double __add_a1_mul_sqrt__lpar__add_a1_pow_4_mul_a2_pow_4_add_a1_pow_4_mul_a2_pow_2_mul_lever_pow_2_add_2_mul_a1_pow_3_mul_a2_pow_3_mul_lever_pow_2_mul_sin__lpar_theta0_rpar___pow_2_add_2_mul_a1_pow_3_mul_a2_mul_lever_pow_4_mul_sin__lpar_theta0_rpar___pow_2_add_a1_pow_2_mul_a2_pow_4_mul_lever_pow_2_add_2_mul_a1_pow_2_mul_a2_pow_2_mul_lever_pow_4_mul_sin__lpar_theta0_rpar___pow_2_add_2_mul_a1_pow_2_mul_lever_pow_6_mul_sin__lpar_theta0_rpar___pow_2_add_a1_pow_2_mul_lever_pow_6_add_2_mul_a1_mul_a2_pow_3_mul_lever_pow_4_mul_sin__lpar_theta0_rpar___pow_2_add_2_mul_a1_mul_a2_mul_lever_pow_6_mul_sin__lpar_theta0_rpar___pow_2_add_2_mul_a2_pow_2_mul_lever_pow_6_mul_sin__lpar_theta0_rpar___pow_2_add_a2_pow_2_mul_lever_pow_6_add_2_mul_lever_pow_8_mul_sin__lpar_theta0_rpar___pow_2_add_lever_pow_8_rpar__ = 0;
    double __add_a1_pow_2_mul_lever_pow_3_mul_sin__lpar_theta0_rpar__ = 0;
    double _a1_pow_3_mul_a2_mul_lever_mul_sin__lpar_theta0_rpar__ = 0;
    double _a1_pow_3_mul_a2_mul_lever_mul_sin__lpar_theta0_rpar___add_a1_pow_2_mul_lever_pow_3_mul_sin__lpar_theta0_rpar___add_a1_mul_a2_mul_lever_pow_3_mul_sin__lpar_theta0_rpar___add_a1_mul_sqrt__lpar__add_a1_pow_4_mul_a2_pow_4_add_a1_pow_4_mul_a2_pow_2_mul_lever_pow_2_add_2_mul_a1_pow_3_mul_a2_pow_3_mul_lever_pow_2_mul_sin__lpar_theta0_rpar___pow_2_add_2_mul_a1_pow_3_mul_a2_mul_lever_pow_4_mul_sin__lpar_theta0_rpar___pow_2_add_a1_pow_2_mul_a2_pow_4_mul_lever_pow_2_add_2_mul_a1_pow_2_mul_a2_pow_2_mul_lever_pow_4_mul_sin__lpar_theta0_rpar___pow_2_add_2_mul_a1_pow_2_mul_lever_pow_6_mul_sin__lpar_theta0_rpar___pow_2_add_a1_pow_2_mul_lever_pow_6_add_2_mul_a1_mul_a2_pow_3_mul_lever_pow_4_mul_sin__lpar_theta0_rpar___pow_2_add_2_mul_a1_mul_a2_mul_lever_pow_6_mul_sin__lpar_theta0_rpar___pow_2_add_2_mul_a2_pow_2_mul_lever_pow_6_mul_sin__lpar_theta0_rpar___pow_2_add_a2_pow_2_mul_lever_pow_6_add_2_mul_lever_pow_8_mul_sin__lpar_theta0_rpar___pow_2_add_lever_pow_8_rpar___add_lever_pow_5_mul_sin__lpar_theta0_rpar__ = 0;
    double _2_mul_lever_mul___lpar_a1_pow_3_mul_a2_mul_lever_mul_sin__lpar_theta0_rpar___add_a1_pow_2_mul_lever_pow_3_mul_sin__lpar_theta0_rpar___add_a1_mul_a2_mul_lever_pow_3_mul_sin__lpar_theta0_rpar___add_a1_mul_sqrt__lpar__add_a1_pow_4_mul_a2_pow_4_add_a1_pow_4_mul_a2_pow_2_mul_lever_pow_2_add_2_mul_a1_pow_3_mul_a2_pow_3_mul_lever_pow_2_mul_sin__lpar_theta0_rpar___pow_2_add_2_mul_a1_pow_3_mul_a2_mul_lever_pow_4_mul_sin__lpar_theta0_rpar___pow_2_add_a1_pow_2_mul_a2_pow_4_mul_lever_pow_2_add_2_mul_a1_pow_2_mul_a2_pow_2_mul_lever_pow_4_mul_sin__lpar_theta0_rpar___pow_2_add_2_mul_a1_pow_2_mul_lever_pow_6_mul_sin__lpar_theta0_rpar___pow_2_add_a1_pow_2_mul_lever_pow_6_add_2_mul_a1_mul_a2_pow_3_mul_lever_pow_4_mul_sin__lpar_theta0_rpar___pow_2_add_2_mul_a1_mul_a2_mul_lever_pow_6_mul_sin__lpar_theta0_rpar___pow_2_add_2_mul_a2_pow_2_mul_lever_pow_6_mul_sin__lpar_theta0_rpar___pow_2_add_a2_pow_2_mul_lever_pow_6_add_2_mul_lever_pow_8_mul_sin__lpar_theta0_rpar___pow_2_add_lever_pow_8_rpar___add_lever_pow_5_mul_sin__lpar_theta0_rpar___rpar___mul_sin__lpar_theta0_rpar___div___lpar_sqrt__lpar__add_a1_pow_2_add_lever_pow_2_rpar___mul___lpar__add_a1_pow_2_mul_a2_pow_2_add_lever_pow_4_rpar___rpar__ = 0;
    double _a1_mul_a2 = 0;
    double _a1_mul_a2_add_lever_pow_2 = 0;
    double _1_div___lpar_a1_mul_a2_add_lever_pow_2_rpar__ = 0;
    double __add_lever_pow_4 = 0;
    double _a1_pow_2_mul_a2_pow_2 = 0;
    double _a1_pow_2_mul_a2_pow_2_add_lever_pow_4 = 0;
    double _cos__lpar_theta0_rpar__ = 0;
    double _cos__lpar_theta0_rpar___pow_2 = 0;
    double __add_2_mul_lever_pow_4_mul_cos__lpar_theta0_rpar___pow_2 = 0;
    double _a1_pow_2_mul_lever_pow_2_mul_cos__lpar_theta0_rpar___pow_2 = 0;
    double _a2_pow_2_mul_lever_pow_2_mul_cos__lpar_theta0_rpar___pow_2 = 0;
    double __add_a1_pow_2_mul_a2_pow_2_add_a1_pow_2_mul_lever_pow_2_mul_cos__lpar_theta0_rpar___pow_2_add_a2_pow_2_mul_lever_pow_2_mul_cos__lpar_theta0_rpar___pow_2_add_2_mul_lever_pow_4_mul_cos__lpar_theta0_rpar___pow_2_add_lever_pow_4 = 0;
    double ___lpar_a1_pow_2_mul_a2_pow_2_add_lever_pow_4_rpar___mul___lpar__add_a1_pow_2_mul_a2_pow_2_add_a1_pow_2_mul_lever_pow_2_mul_cos__lpar_theta0_rpar___pow_2_add_a2_pow_2_mul_lever_pow_2_mul_cos__lpar_theta0_rpar___pow_2_add_2_mul_lever_pow_4_mul_cos__lpar_theta0_rpar___pow_2_add_lever_pow_4_rpar__ = 0;
    double _a1_mul_lever_pow_2 = 0;
    double _a2_mul_lever_pow_2 = 0;
    double __add_a1_mul_a2_pow_2 = 0;
    double __add_a1_pow_2_mul_a2 = 0;
    double __add_a1_pow_2_mul_a2_add_a1_mul_a2_pow_2_add_a1_mul_lever_pow_2_add_a2_mul_lever_pow_2 = 0;
    double ___lpar__add_a1_pow_2_mul_a2_add_a1_mul_a2_pow_2_add_a1_mul_lever_pow_2_add_a2_mul_lever_pow_2_rpar___pow_2 = 0;
    double _lever_pow_2_mul___lpar__add_a1_pow_2_mul_a2_add_a1_mul_a2_pow_2_add_a1_mul_lever_pow_2_add_a2_mul_lever_pow_2_rpar___pow_2_mul_sin__lpar_theta0_rpar___pow_2 = 0;
    double _lever_pow_2_mul___lpar__add_a1_pow_2_mul_a2_add_a1_mul_a2_pow_2_add_a1_mul_lever_pow_2_add_a2_mul_lever_pow_2_rpar___pow_2_mul_sin__lpar_theta0_rpar___pow_2_add___lpar_a1_pow_2_mul_a2_pow_2_add_lever_pow_4_rpar___mul___lpar__add_a1_pow_2_mul_a2_pow_2_add_a1_pow_2_mul_lever_pow_2_mul_cos__lpar_theta0_rpar___pow_2_add_a2_pow_2_mul_lever_pow_2_mul_cos__lpar_theta0_rpar___pow_2_add_2_mul_lever_pow_4_mul_cos__lpar_theta0_rpar___pow_2_add_lever_pow_4_rpar__ = 0;
    double _sqrt__lpar_lever_pow_2_mul___lpar__add_a1_pow_2_mul_a2_add_a1_mul_a2_pow_2_add_a1_mul_lever_pow_2_add_a2_mul_lever_pow_2_rpar___pow_2_mul_sin__lpar_theta0_rpar___pow_2_add___lpar_a1_pow_2_mul_a2_pow_2_add_lever_pow_4_rpar___mul___lpar__add_a1_pow_2_mul_a2_pow_2_add_a1_pow_2_mul_lever_pow_2_mul_cos__lpar_theta0_rpar___pow_2_add_a2_pow_2_mul_lever_pow_2_mul_cos__lpar_theta0_rpar___pow_2_add_2_mul_lever_pow_4_mul_cos__lpar_theta0_rpar___pow_2_add_lever_pow_4_rpar___rpar__ = 0;
    double ___lpar_a1_mul_a2_add_lever_pow_2_rpar___mul_sqrt__lpar_lever_pow_2_mul___lpar__add_a1_pow_2_mul_a2_add_a1_mul_a2_pow_2_add_a1_mul_lever_pow_2_add_a2_mul_lever_pow_2_rpar___pow_2_mul_sin__lpar_theta0_rpar___pow_2_add___lpar_a1_pow_2_mul_a2_pow_2_add_lever_pow_4_rpar___mul___lpar__add_a1_pow_2_mul_a2_pow_2_add_a1_pow_2_mul_lever_pow_2_mul_cos__lpar_theta0_rpar___pow_2_add_a2_pow_2_mul_lever_pow_2_mul_cos__lpar_theta0_rpar___pow_2_add_2_mul_lever_pow_4_mul_cos__lpar_theta0_rpar___pow_2_add_lever_pow_4_rpar___rpar__ = 0;
    double _a1_add_a2 = 0;
    double _lever_mul___lpar_a1_add_a2_rpar___mul___lpar__add_a1_pow_2_mul_a2_pow_2_add_lever_pow_4_rpar___mul_sin__lpar_theta0_rpar__ = 0;
    double _lever_mul___lpar_a1_add_a2_rpar___mul___lpar__add_a1_pow_2_mul_a2_pow_2_add_lever_pow_4_rpar___mul_sin__lpar_theta0_rpar___add___lpar_a1_mul_a2_add_lever_pow_2_rpar___mul_sqrt__lpar_lever_pow_2_mul___lpar__add_a1_pow_2_mul_a2_add_a1_mul_a2_pow_2_add_a1_mul_lever_pow_2_add_a2_mul_lever_pow_2_rpar___pow_2_mul_sin__lpar_theta0_rpar___pow_2_add___lpar_a1_pow_2_mul_a2_pow_2_add_lever_pow_4_rpar___mul___lpar__add_a1_pow_2_mul_a2_pow_2_add_a1_pow_2_mul_lever_pow_2_mul_cos__lpar_theta0_rpar___pow_2_add_a2_pow_2_mul_lever_pow_2_mul_cos__lpar_theta0_rpar___pow_2_add_2_mul_lever_pow_4_mul_cos__lpar_theta0_rpar___pow_2_add_lever_pow_4_rpar___rpar__ = 0;
    double _2_mul_lever_mul___lpar_lever_mul___lpar_a1_add_a2_rpar___mul___lpar__add_a1_pow_2_mul_a2_pow_2_add_lever_pow_4_rpar___mul_sin__lpar_theta0_rpar___add___lpar_a1_mul_a2_add_lever_pow_2_rpar___mul_sqrt__lpar_lever_pow_2_mul___lpar__add_a1_pow_2_mul_a2_add_a1_mul_a2_pow_2_add_a1_mul_lever_pow_2_add_a2_mul_lever_pow_2_rpar___pow_2_mul_sin__lpar_theta0_rpar___pow_2_add___lpar_a1_pow_2_mul_a2_pow_2_add_lever_pow_4_rpar___mul___lpar__add_a1_pow_2_mul_a2_pow_2_add_a1_pow_2_mul_lever_pow_2_mul_cos__lpar_theta0_rpar___pow_2_add_a2_pow_2_mul_lever_pow_2_mul_cos__lpar_theta0_rpar___pow_2_add_2_mul_lever_pow_4_mul_cos__lpar_theta0_rpar___pow_2_add_lever_pow_4_rpar___rpar___rpar___mul_sin__lpar_theta0_rpar___div___lpar___lpar_a1_mul_a2_add_lever_pow_2_rpar___mul___lpar__add_a1_pow_2_mul_a2_pow_2_add_lever_pow_4_rpar___rpar__ = 0;

};

